import pyglet
import json
from datetime import datetime
from pyglet import shapes, text
from pyglet.gl import glClearColor
from driver import Driver
from simulation_state import SimulationState

# Create application window with the given width and height
window = pyglet.window.Window(1400, 800)

# Create a batch group for optimized rendering
batch = pyglet.graphics.Batch()

# Set background colour
glClearColor(255, 255, 255, 1)

# Load drivers
with open('../../data/open_f1/drivers.json', 'r') as file:
    drivers = {
        driver["driver_number"]: Driver(driver["driver_number"], driver["name_acronym"], driver["team_colour"], 0, 0, 0)
        for driver in json.load(file)
    }

# Load in racer locations
with open('../../data/open_f1/locations.json', 'r') as file:
    locations_data = json.load(file)

# Load in position data
with open('../../data/open_f1/positions.json', 'r') as file:
    position_data = json.load(file)

print("Successfully loaded drivers, locations, and position data")

# Convert UTC times to timestamps
for ld in locations_data:
    ld["time"] = datetime.timestamp(datetime.fromisoformat(ld["date"]))

# Sort location data by time, and then driver
locations_data.sort(key=lambda x: (x["time"], x["driver_number"]))

for pd in position_data:
    pd["time"] = datetime.timestamp(datetime.fromisoformat(pd["date"]))

# Sort position data by time, and then driver
position_data.sort(key=lambda x: (x["time"], x["driver_number"]))

# Sample points along the track for rendering
track_location_data = [x for x in locations_data if x["driver_number"] == 1][:800][::4]

# Determine starting index for the simulation
starting_index = 17500

# Resize and position the race within the application window
alpha = 0.08
initial_x = locations_data[starting_index]["x"] * alpha
initial_y = locations_data[starting_index]["y"] * alpha
for ld in locations_data:
    # Rescale x and y coordinates
    ld["x"] = ld["x"] * alpha
    ld["y"] = ld["y"] * alpha

    # Add translational offset
    ld["x"] -= initial_x
    ld["y"] -= initial_y

    ld["x"] += 1250
    ld["y"] += 475

# Define shape of the race track
track_joints = tuple(shapes.Circle(x=track_point["x"], y=track_point["y"], radius=4, color=(0,0,0), batch=batch) for track_point in track_location_data)

track_lines = tuple(shapes.Line(x=track_location_data[i]["x"], y=track_location_data[i]["y"], x2=track_location_data[i+1]["x"], y2=track_location_data[i+1]["y"], thickness=7, color=(0,0,0), batch=batch) for i in range(len(track_location_data)-1))

# Load Formula 1 logo
f1_logo = pyglet.image.load("assets/formula-1-logo-0.png")
f1_sprite = pyglet.sprite.Sprite(f1_logo, x=25, y=520, batch=batch)
f1_sprite.scale = 0.08

# Set up the initial state for the simulation
start_time = datetime.timestamp(datetime.fromisoformat(locations_data[starting_index]["date"]))
state = SimulationState(drivers, start_time)

## Functions which are ran periodically to create the simulation
def update(dt):
    # Increment elapsed time
    time_acceleration = 2.5
    state.time += time_acceleration * dt

    # "Catch up" on passed events by updating driver locations and positions
    while locations_data[state.location_index]["time"] < state.time:
        ld = locations_data[state.location_index]
        driver = state.drivers[ld["driver_number"]]
        driver.x = ld["x"]
        driver.y = ld["y"]

        driver.driver_icon.x = driver.x
        driver.driver_icon.y = driver.y
        driver.driver_name.x = driver.x
        driver.driver_name.y = driver.y

        state.location_index += 1

    if position_data[state.position_index]["time"] < state.time:
        while position_data[state.position_index]["time"] < state.time:
            pd = position_data[state.position_index]
            driver = state.drivers[pd["driver_number"]]
            driver.position = pd["position"]
            state.position_index += 1

        state.ordered_drivers.sort(key=lambda driver: driver.position, reverse=True)

@window.event
def on_draw():
    # Clear background
    window.clear()

    # Draw track and Formula 1 logo
    batch.draw()

    # Draw drivers
    for driver in state.ordered_drivers:
        driver.draw()

# Schedule periodic updating of racer locations
pyglet.clock.schedule_interval(update, 1/120)

# Load live commentary generated by the model
commentary = pyglet.media.load("assets/ai_generated_f1_commentary.wav", streaming=False)
commentary.play()

# Start the application
try:
    pyglet.app.run()
except KeyboardInterrupt:
    print()
